name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 20

      - name: Run RSpec in Docker
        run: docker-compose exec web bundle exec rspec

      - name: Shut down Docker Compose
        run: docker-compose down
